### ISSUE TITLE
Question: Do The Items Despawn?

### ISSUE THREAD

**Issue by K4N0** [UnderMybrella/Fidelis#1]
I wanted to ask if the items despawn after a set amount of time or if they will remain in the world forever. Also do they get cleared by Clearlag or /killall all commands?

**Comment by UnderMybrella** [comment]
Honestly, it all depends on a few things...
1) If the items would expire (5 minute time limit) and the player is online (server scenario) then the item is returned to the players inventory. If they're not, then the item gets extra time. There's no current cap on this (that I'm aware of)
2) If a command is executed, such as killall, if they kill all entities, then the items _should_ return back to the owners inventory, if it's coded right on their end. /cofh killall \* seems to return the item to the inventory
3) ClearLag should do a similar thing as the command

**Comment by K4N0** [comment]
Do they have to be online? and or if their inventory is full? I'll do some testing with it. Thanks for the reply.

**Comment by UnderMybrella** [comment]
If they're not online there doesn't seem to be a way to add it to their inventory, and if their inventory is full the item either
a) stays where it is if it's an expiration event
or
b) moves to the player if it's a death event
