### ISSUE TITLE
Modded gui

### ISSUE THREAD

**Issue by zHawky** [UnderMybrella/Fidelis#2]
When im found mod im think, finally, i found soulbound without ArsMagica and EnderIO
but one thing, maybe you take a look on modded gui such as Aether2 and maybe compatiblity with Adventure backpacks?

here the links
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289717-alpha-aether-ii-genesis-of-the-void-party-fixes

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2252109-wip-adventure-backpack-mod-beta-0-8c-updated

**Comment by UnderMybrella** [comment]
If you're talking about making soulbound items in those inventories persist past death, then sorry, that's not getting implemented.
I already considered this with other mods, but the effort far outweighed any potential benefit. On top of that, a key feature is soulbound items would remain in their inventory slot after death. With things like backpacks there's no standard slot, which nullifies a large part. 
Honestly, in 99% of cases, you're better off soulbinding the backpack itself. Yes, armour and baubles can be soulbound to a player, so take advantage of that.

However, if you're talking about something other than persistance through inventories, feel free to comment again and I'll think about it.
