### ISSUE TITLE
Crash on a Server

### ISSUE THREAD

**Issue by K4N0** [UnderMybrella/Fidelis#3]
http://pastebin.com/x6JetWvL

Put your mod on the server, attempted to souldbind a diamond sword with the default config, crash.

**Comment by UnderMybrella** [comment]
Yeah, okay that makes sense. I've uploaded a new release to curse, should be up within the hour. Sorry about that, stupid mistake on my part really.

**Comment by K4N0** [comment]
Very nice. Thanks for the quick fix.
Modpack permissions?
http://www.technicpack.net/modpack/hardvanilla.779656

**Comment by UnderMybrella** [comment]
Feel free; do what you like with it. Hope the pack goes well.
